FROM golang:1.21.5-bullseye AS builder

WORKDIR /build
ENV GOPROXY https://goproxy.cn

COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

RUN cd ./cmd/remote-storage && go build -v -o remote-storage


FROM debian:bullseye-slim AS runner

WORKDIR /app
COPY --from=builder remote-storage /app/jaeger-remote-storage
COPY ./cmd/remote-storage/config.yaml /app

CMD ["/app/jaeger-remote-storage"]